**<center> <span style="color:#0F52BA;font-family:serif; font-size:34px;"> TELECOM CUSTOMER CHURN PREDICTION MODEL 📈</span> </center>**

##

In [5]:
# Importing the required libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

In [6]:
# Loading the dataset

df = pd.read_csv('Telco-Customer-Churn.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,Yes,Electronic check,29.85,29.85,No,NaN,NaN,NaN,NaN,NaN
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,Mailed check,56.95,1889.5,No,NaN,NaN,NaN,NaN,NaN
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,Yes,Mailed check,53.85,108.15,Yes,NaN,NaN,NaN,NaN,NaN
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,Bank transfer (automatic),42.30,1840.75,No,NaN,NaN,NaN,NaN,NaN
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,Yes,Electronic check,70.70,151.65,Yes,NaN,NaN,NaN,NaN,NaN

### Data Exploration & Cleaning

In [7]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn',
       'Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24',
       'Unnamed: 25'],
      dtype='str')

In [8]:
df.shape

(7043, 26)

In [9]:
# Checking the dataset structure and data types

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
 21  Unnamed: 21       0 non-null      float64
 22  Unnamed: 22       0 non-null      float64
 23  Unnamed: 23       0 non-null      float64
 24  Unnamed: 24       0 non-null      float64
 25  Unnamed: 25       0 non-null      float64
dtypes: float64(6), int64(2), str(18)
memory usage: 2.1 MB

In [10]:
# Checking for missing values in each column

df.isnull().sum()

customerID             0
gender                 0
SeniorCitizen          0
Partner                0
Dependents             0
tenure                 0
PhoneService           0
MultipleLines          0
InternetService        0
OnlineSecurity         0
OnlineBackup           0
DeviceProtection       0
TechSupport            0
StreamingTV            0
StreamingMovies        0
Contract               0
PaperlessBilling       0
PaymentMethod          0
MonthlyCharges         0
TotalCharges           0
Churn                  0
Unnamed: 21         7043
Unnamed: 22         7043
Unnamed: 23         7043
Unnamed: 24         7043
Unnamed: 25         7043
dtype: int64

In [11]:
# Checking for duplicate rows

df.duplicated().sum()

np.int64(0)

In [12]:
df.drop(columns=['Unnamed: 21', 'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24','Unnamed: 25'], inplace=True)

In [13]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='str')

In [14]:
# drop customerID is not necessary for analysis

df = df.drop(columns=['customerID'])

In [15]:
# Checking for non-numeric values in TotalCharges

totalcharges_numeric = pd.to_numeric(
    df['TotalCharges'],
    errors='coerce'
)

invalid_totalcharges = df.loc[
    totalcharges_numeric.isna(),
    'TotalCharges'
]

print("Number of non-numeric values:", invalid_totalcharges.shape[0])
print("Non-numeric values:", invalid_totalcharges.unique())

Number of non-numeric values: 11
Non-numeric values: <ArrowStringArray>
[' ']
Length: 1, dtype: str

In [16]:
# Replacing blank spaces with missing values

df['TotalCharges'] = df['TotalCharges'].replace(' ', np.nan)

In [17]:
# Converting TotalCharges from string to numeric

df['TotalCharges'] = pd.to_numeric(df['TotalCharges'])

print("TotalCharges data type:", df['TotalCharges'].dtype)

TotalCharges data type: float64

In [18]:
# Filling missing TotalCharges with 0 for customers with zero tenure

df['TotalCharges'] = df['TotalCharges'].fillna(0)

print(
    "Missing values in TotalCharges after cleaning:",
    df['TotalCharges'].isnull().sum()
)

Missing values in TotalCharges after cleaning: 0

* The missing values in TotalCharges were found only for customers with zero tenure. Since these customers had just joined the service and had no recorded tenure, their TotalCharges were treated as 0 rather than removing the records.

In [19]:
df.dtypes

gender                  str
SeniorCitizen         int64
Partner                 str
Dependents              str
tenure                int64
PhoneService            str
MultipleLines           str
InternetService         str
OnlineSecurity          str
OnlineBackup            str
DeviceProtection        str
TechSupport             str
StreamingTV             str
StreamingMovies         str
Contract                str
PaperlessBilling        str
PaymentMethod           str
MonthlyCharges      float64
TotalCharges        float64
Churn                   str
dtype: object

In [20]:
# Checking unique values in categorical columns

categorical_cols = df.select_dtypes(include='str').columns

for col in categorical_cols:
    print(f"\n{col}:")
    print(df[col].unique())

gender:
<ArrowStringArray>
['Female', 'Male']
Length: 2, dtype: str

Partner:
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

Dependents:
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

PhoneService:
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

MultipleLines:
<ArrowStringArray>
['No phone service', 'No', 'Yes']
Length: 3, dtype: str

InternetService:
<ArrowStringArray>
['DSL', 'Fiber optic', 'No']
Length: 3, dtype: str

OnlineSecurity:
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

OnlineBackup:
<ArrowStringArray>
['Yes', 'No', 'No internet service']
Length: 3, dtype: str

DeviceProtection:
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

TechSupport:
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

StreamingTV:
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

StreamingMovies:
<ArrowStringArray>
['No', 'Yes', 'No internet service']
Length: 3, dtype: str

Contract:
<ArrowStringArray>
['Month-to-month', 'One year', 'Two year']
Length: 3, dtype: str

PaperlessBilling:
<ArrowStringArray>
['Yes', 'No']
Length: 2, dtype: str

PaymentMethod:
<ArrowStringArray>
[         'Electronic check',              'Mailed check',
 'Bank transfer (automatic)',   'Credit card (automatic)']
Length: 4, dtype: str

Churn:
<ArrowStringArray>
['No', 'Yes']
Length: 2, dtype: str

### Exploratory Data Analysis (EDA)

* The main objective of this analysis is to identify the factors that are associated with customer churn and understand the characteristics of customers who are more likely to leave the service.

* The analysis will investigate customer demographics, service usage, contract type, payment methods, tenure, and charges to identify patterns and relationships with churn.

* What is the overall churn rate?
* Which customer characteristics are associated with churn?
* Does customer tenure affect churn?
* Does the type of contract affect churn?
* Do monthly and total charges differ between churned and retained customers?
* Which services are associated with higher or lower churn?

In [21]:
# Displaying the number of rows and columns in the cleaned dataset

print("Number of customers:", df.shape[0])
print("Number of features:", df.shape[1])

Number of customers: 7043
Number of features: 20

In [22]:
# Calculating the number and percentage of customers in each churn category

churn_count = df['Churn'].value_counts()
churn_percentage = df['Churn'].value_counts(normalize=True) * 100

print("Number of customers by churn status:")
print(churn_count)

print("\nPercentage of customers by churn status:")
print(churn_percentage.round(2))

Number of customers by churn status:
Churn
No     5174
Yes    1869
Name: count, dtype: int64

Percentage of customers by churn status:
Churn
No     73.46
Yes    26.54
Name: proportion, dtype: float64

In [23]:
# Calculating churn rate by gender

gender_churn = (
    df.groupby('gender')['Churn']
    .apply(lambda x: (x == 'Yes').mean() * 100)
    .reset_index(name='Churn Rate')
)

gender_churn

   gender  Churn Rate
0  Female   26.920872
1    Male   26.160338

In [24]:
# Visualizing churn rate by gender

import plotly.express as px

fig = px.bar(
    gender_churn,
    x='gender',
    y='Churn Rate',
    text='Churn Rate',
    title='Churn Rate by Gender',
    labels={
        'gender': 'Gender',
        'Churn Rate': 'Churn Rate (%)'
    }
)

fig.update_traces(
    texttemplate='%{text:.1f}%',
    textposition='outside'
)

fig.update_layout(
    yaxis_title='Churn Rate (%)',
    xaxis_title='Gender'
)

fig.show()

In [25]:
# Calculating churn rate by senior citizen status

senior_churn = (
    df.groupby('SeniorCitizen')['Churn']
    .apply(lambda x: (x == 'Yes').mean() * 100)
    .reset_index(name='Churn Rate')
)

senior_churn['SeniorCitizen'] = senior_churn['SeniorCitizen'].map({
    0: 'Non-Senior Citizen',
    1: 'Senior Citizen'
})

senior_churn

        SeniorCitizen  Churn Rate
0  Non-Senior Citizen   23.606168
1      Senior Citizen   41.681261

In [26]:
# Visualizing churn rate by senior citizen status

fig = px.bar(
    senior_churn,
    x='SeniorCitizen',
    y='Churn Rate',
    text='Churn Rate',
    title='Churn Rate by Senior Citizen Status',
    labels={
        'SeniorCitizen': 'Customer Type',
        'Churn Rate': 'Churn Rate (%)'
    }
)

fig.update_traces(
    texttemplate='%{text:.1f}%',
    textposition='outside'
)

fig.update_layout(
    yaxis_title='Churn Rate (%)',
    xaxis_title='Customer Type'
)

fig.show()

In [27]:
# Creating tenure categories to analyze churn across different customer lifecycle stages

df['TenureGroup'] = pd.cut(
    df['tenure'],
    bins=[-1, 12, 36, float('inf')],
    labels=['New Customers', 'Medium Tenure', 'Long Tenure']
)

In [28]:
# Calculating churn rate by tenure group

tenure_churn = (
    df.groupby('TenureGroup', observed=True)['Churn']
    .apply(lambda x: (x == 'Yes').mean() * 100)
    .reset_index(name='Churn Rate')
)

tenure_churn

     TenureGroup  Churn Rate
0  New Customers   47.438243
1  Medium Tenure   25.538793
2    Long Tenure   11.929357

In [29]:
# Visualizing churn rate by tenure group

fig = px.bar(
    tenure_churn,
    x='TenureGroup',
    y='Churn Rate',
    text='Churn Rate',
    title='Churn Rate by Tenure Group',
    labels={
        'TenureGroup': 'Tenure Group',
        'Churn Rate': 'Churn Rate (%)'
    }
)

fig.update_traces(
    texttemplate='%{text:.1f}%',
    textposition='outside'
)

fig.update_layout(
    yaxis_title='Churn Rate (%)',
    xaxis_title='Tenure Group'
)

fig.show()

In [30]:
# Comparing MonthlyCharges between churned and retained customers

monthly_charges_summary = (
    df.groupby('Churn')['MonthlyCharges']
    .agg(['count', 'mean', 'median', 'min', 'max'])
    .round(2)
)

monthly_charges_summary

       count   mean  median    min     max
Churn
No      5174  61.27   64.43  18.25  118.75
Yes     1869  74.44   79.65  18.85  118.35

In [31]:
# Visualizing MonthlyCharges distribution by churn status

fig = px.box(
    df,
    x='Churn',
    y='MonthlyCharges',
    color='Churn',
    points=False,
    title='Monthly Charges Distribution by Churn Status',
    labels={
        'Churn': 'Churn Status',
        'MonthlyCharges': 'Monthly Charges'
    }
)

fig.update_layout(
    xaxis_title='Churn Status',
    yaxis_title='Monthly Charges'
)

fig.show()

In [32]:
# Calculating churn rate by contract type

contract_churn = (
    df.groupby('Contract')['Churn']
    .apply(lambda x: (x == 'Yes').mean() * 100)
    .reset_index(name='Churn Rate')
    .sort_values('Churn Rate', ascending=False)
)

contract_churn

         Contract  Churn Rate
0  Month-to-month   42.709677
1        One year   11.269518
2        Two year    2.831858

In [33]:
# Visualizing churn rate by contract type

fig = px.bar(
    contract_churn,
    x='Contract',
    y='Churn Rate',
    text='Churn Rate',
    title='Churn Rate by Contract Type',
    labels={
        'Contract': 'Contract Type',
        'Churn Rate': 'Churn Rate (%)'
    }
)

fig.update_traces(
    texttemplate='%{text:.1f}%',
    textposition='outside'
)

fig.update_layout(
    yaxis_title='Churn Rate (%)',
    xaxis_title='Contract Type'
)

fig.show()

In [34]:
# Calculating churn rate by internet service

internet_churn = (
    df.groupby('InternetService')['Churn']
    .apply(lambda x: (x == 'Yes').mean() * 100)
    .reset_index(name='Churn Rate')
    .sort_values('Churn Rate', ascending=False)
)

internet_churn

  InternetService  Churn Rate
1     Fiber optic   41.892765
0             DSL   18.959108
2              No    7.404980

In [35]:
# Visualizing churn rate by internet service

fig = px.bar(
    internet_churn,
    x='InternetService',
    y='Churn Rate',
    text='Churn Rate',
    title='Churn Rate by Internet Service',
    labels={
        'InternetService': 'Internet Service',
        'Churn Rate': 'Churn Rate (%)'
    }
)

fig.update_traces(
    texttemplate='%{text:.1f}%',
    textposition='outside'
)

fig.update_layout(
    yaxis_title='Churn Rate (%)',
    xaxis_title='Internet Service'
)

fig.show()

In [36]:
# Calculating churn rate by payment method

payment_churn = (
    df.groupby('PaymentMethod')['Churn']
    .apply(lambda x: (x == 'Yes').mean() * 100)
    .reset_index(name='Churn Rate')
    .sort_values('Churn Rate', ascending=False)
)

payment_churn

               PaymentMethod  Churn Rate
2           Electronic check   45.285412
3               Mailed check   19.106700
0  Bank transfer (automatic)   16.709845
1    Credit card (automatic)   15.243101

In [37]:
# Visualizing churn rate by payment method

fig = px.bar(
    payment_churn,
    x='PaymentMethod',
    y='Churn Rate',
    text='Churn Rate',
    title='Churn Rate by Payment Method',
    labels={
        'PaymentMethod': 'Payment Method',
        'Churn Rate': 'Churn Rate (%)'
    }
)

fig.update_traces(
    texttemplate='%{text:.1f}%',
    textposition='outside'
)

fig.update_layout(
    yaxis_title='Churn Rate (%)',
    xaxis_title='Payment Method',
    xaxis_tickangle=-20
)

fig.show()

In [38]:
# Comparing TotalCharges between churned and retained customers

total_charges_summary = (
    df.groupby('Churn')['TotalCharges']
    .agg(['count', 'mean', 'median', 'min', 'max'])
    .round(2)
)

total_charges_summary

       count     mean   median    min      max
Churn
No      5174  2549.91  1679.52   0.00  8672.45
Yes     1869  1531.80   703.55  18.85  8684.80

In [39]:
# Visualizing TotalCharges distribution by churn status

fig = px.box(
    df,
    x='Churn',
    y='TotalCharges',
    color='Churn',
    points=False,
    title='Total Charges Distribution by Churn Status',
    labels={
        'Churn': 'Churn Status',
        'TotalCharges': 'Total Charges'
    }
)

fig.update_layout(
    xaxis_title='Churn Status',
    yaxis_title='Total Charges'
)

fig.show()

In [40]:
# Selecting numerical variables for correlation analysis

numerical_cols = ['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

correlation_matrix = df[numerical_cols].corr()

correlation_matrix

                SeniorCitizen    tenure  MonthlyCharges  TotalCharges
SeniorCitizen        1.000000  0.016567        0.220173      0.103006
tenure               0.016567  1.000000        0.247900      0.826178
MonthlyCharges       0.220173  0.247900        1.000000      0.651174
TotalCharges         0.103006  0.826178        0.651174      1.000000

In [41]:
# Visualizing correlations between numerical variables

fig = px.imshow(
    correlation_matrix,
    text_auto='.2f',
    aspect='auto',
    title='Correlation Matrix of Numerical Variables',
    labels=dict(
        x='Variables',
        y='Variables',
        color='Correlation'
    )
)

fig.show()

* ### Feature Engineering

In [42]:
# Converting the target variable Churn into numerical values

df['Churn'] = df['Churn'].map({
    'No': 0,
    'Yes': 1
})

In [43]:
df['Churn'].value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

In [44]:
# Creating a new feature representing the total number of subscribed services

service_cols = [
    'OnlineSecurity',
    'OnlineBackup',
    'DeviceProtection',
    'TechSupport',
    'StreamingTV',
    'StreamingMovies'
]

df['TotalServices'] = (df[service_cols] == 'Yes').sum(axis=1)

df[['TotalServices', 'Churn']].head()

   TotalServices  Churn
0              1      0
1              2      0
2              2      1
3              3      0
4              0      1

In [45]:
# Creating a feature representing the average monthly spend

df['AverageMonthlySpend'] = np.where(
    df['tenure'] > 0,
    df['TotalCharges'] / df['tenure'],
    df['MonthlyCharges']
)

df[['tenure', 'MonthlyCharges', 'TotalCharges', 'AverageMonthlySpend']].head()

   tenure  MonthlyCharges  TotalCharges  AverageMonthlySpend
0       1           29.85         29.85            29.850000
1      34           56.95       1889.50            55.573529
2       2           53.85        108.15            54.075000
3      45           42.30       1840.75            40.905556
4       2           70.70        151.65            75.825000

In [46]:
# Removing the feature created only for exploratory analysis

df = df.drop(columns=['TenureGroup'])

* ### Data Preprocessing

In [47]:
# Separating the features from the target variable

X = df.drop(columns=['Churn'])
y = df['Churn']

In [48]:
# Displaying the selected features

print("Number of features:", X.shape[1])
print("\nSelected features:")
print(X.columns.tolist())

Number of features: 21

Selected features:
['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'TotalServices', 'AverageMonthlySpend']

In [49]:
# Identifying numerical and categorical features

numerical_features = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_features = X.select_dtypes(include=['str']).columns.tolist()

print("Numerical features:")
print(numerical_features)

print("\nCategorical features:")
print(categorical_features)

Numerical features:
['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges', 'TotalServices', 'AverageMonthlySpend']

Categorical features:
['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

In [50]:
# Splitting the dataset into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)

Training set shape: (5634, 21)
Testing set shape: (1409, 21)

In [51]:
# Creating preprocessing steps for numerical and categorical features

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline

preprocessor = ColumnTransformer(
    transformers=[
        (
            'num',
            StandardScaler(),
            numerical_features
        ),
        (
            'cat',
            OneHotEncoder(handle_unknown='ignore'),
            categorical_features
        )
    ]
)

In [52]:
# Creating a pipeline combining preprocessing and Logistic Regression

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

logistic_model = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', LogisticRegression(max_iter=1000, random_state=42))
    ]
)

# Training the Logistic Regression model

logistic_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['SeniorCitizen', 'tenure',
                                                   'MonthlyCharges',
                                                   'TotalCharges',
                                                   'TotalServices',
                                                   'AverageMonthlySpend']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', LogisticRegression(max_iter=1000, random_state=42))])

In [53]:
# Training the Logistic Regression model

logistic_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['SeniorCitizen', 'tenure',
                                                   'MonthlyCharges',
                                                   'TotalCharges',
                                                   'TotalServices',
                                                   'AverageMonthlySpend']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', LogisticRegression(max_iter=1000, random_state=42))])

In [54]:
# Making predictions on the test set

y_pred_logistic = logistic_model.predict(X_test)

In [55]:
# Evaluating Logistic Regression performance

logistic_results = {
    'Model': 'Logistic Regression',
    'Accuracy': accuracy_score(y_test, y_pred_logistic),
    'Precision': precision_score(y_test, y_pred_logistic),
    'Recall': recall_score(y_test, y_pred_logistic),
    'F1 Score': f1_score(y_test, y_pred_logistic)
}

logistic_results

{'Model': 'Logistic Regression',
 'Accuracy': 0.8062455642299503,
 'Precision': 0.658307210031348,
 'Recall': 0.5614973262032086,
 'F1 Score': 0.6060606060606061}

In [56]:
# Creating a pipeline combining preprocessing and Random Forest

from sklearn.ensemble import RandomForestClassifier

random_forest_model = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', RandomForestClassifier(
            n_estimators=200,
            random_state=42,
            class_weight='balanced'
        ))
    ]
)

In [57]:
# Training the Random Forest model

random_forest_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['SeniorCitizen', 'tenure',
                                                   'MonthlyCharges',
                                                   'TotalCharges',
                                                   'TotalServices',
                                                   'AverageMonthlySpend']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=200, random_state=42))])

In [58]:
# Making predictions on the test set

y_pred_rf = random_forest_model.predict(X_test)

In [59]:
# Evaluating Random Forest performance

random_forest_results = {
    'Model': 'Random Forest',
    'Accuracy': accuracy_score(y_test, y_pred_rf),
    'Precision': precision_score(y_test, y_pred_rf),
    'Recall': recall_score(y_test, y_pred_rf),
    'F1 Score': f1_score(y_test, y_pred_rf)
}

random_forest_results

{'Model': 'Random Forest',
 'Accuracy': 0.7792760823278921,
 'Precision': 0.6097560975609756,
 'Recall': 0.4679144385026738,
 'F1 Score': 0.529500756429652}

In [60]:
# Creating a pipeline combining preprocessing and Gradient Boosting

from sklearn.ensemble import GradientBoostingClassifier

gradient_boosting_model = Pipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('model', GradientBoostingClassifier(
            random_state=42
        ))
    ]
)

In [61]:
# Training the Gradient Boosting model

gradient_boosting_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['SeniorCitizen', 'tenure',
                                                   'MonthlyCharges',
                                                   'TotalCharges',
                                                   'TotalServices',
                                                   'AverageMonthlySpend']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['gender', 'Partner',
                                                   'Dependents', 'PhoneService',
                                                   'MultipleLines',
                                                   'InternetService',
                                                   'OnlineSecurity',
                                                   'OnlineBackup',
                                                   'DeviceProtection',
                                                   'TechSupport', 'StreamingTV',
                                                   'StreamingMovies',
                                                   'Contract',
                                                   'PaperlessBilling',
                                                   'PaymentMethod'])])),
                ('model', GradientBoostingClassifier(random_state=42))])

In [62]:
# Making predictions on the test set

y_pred_gb = gradient_boosting_model.predict(X_test)

In [63]:
# Evaluating Gradient Boosting performance

gradient_boosting_results = {
    'Model': 'Gradient Boosting',
    'Accuracy': accuracy_score(y_test, y_pred_gb),
    'Precision': precision_score(y_test, y_pred_gb),
    'Recall': recall_score(y_test, y_pred_gb),
    'F1 Score': f1_score(y_test, y_pred_gb)
}

gradient_boosting_results

{'Model': 'Gradient Boosting',
 'Accuracy': 0.801277501774308,
 'Precision': 0.6620689655172414,
 'Recall': 0.5133689839572193,
 'F1 Score': 0.5783132530120482}

In [64]:
# Comparing the performance of the three models

model_results = pd.DataFrame([
    logistic_results,
    random_forest_results,
    gradient_boosting_results
])

model_results.sort_values(
    by='F1 Score',
    ascending=False
)

                 Model  Accuracy  Precision    Recall  F1 Score
0  Logistic Regression  0.806246   0.658307  0.561497  0.606061
2    Gradient Boosting  0.801278   0.662069  0.513369  0.578313
1        Random Forest  0.779276   0.609756  0.467914  0.529501

In [65]:
# Defining hyperparameters for Logistic Regression tuning

from sklearn.model_selection import GridSearchCV

param_grid = {
    'model__C': [0.01, 0.1, 1, 10, 100]}

In [66]:
# Defining hyperparameters for Logistic Regression tuning

param_grid = {
    'model__C': [0.01, 0.1, 1, 10, 100]}

In [67]:
# Creating GridSearchCV for Logistic Regression

grid_search = GridSearchCV(
    estimator=logistic_model,
    param_grid=param_grid,
    scoring='recall',
    cv=5,
    n_jobs=-1
)

In [68]:
# Training GridSearchCV

grid_search.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['SeniorCitizen',
                                                                          'tenure',
                                                                          'MonthlyCharges',
                                                                          'TotalCharges',
                                                                          'TotalServices',
                                                                          'AverageMonthlySpend']),
                                                                        ('cat',
                                                                         OneHotEncoder(handle_unknown='ignore'),
                                                                         ['gender',
                                                                          'Partner',
                                                                          'Dependents',
                                                                          'PhoneService',
                                                                          'MultipleLines',
                                                                          'InternetService',
                                                                          'OnlineSecurity',
                                                                          'OnlineBackup',
                                                                          'DeviceProtection',
                                                                          'TechSupport',
                                                                          'StreamingTV',
                                                                          'StreamingMovies',
                                                                          'Contract',
                                                                          'PaperlessBilling',
                                                                          'PaymentMethod'])])),
                                       ('model',
                                        LogisticRegression(max_iter=1000,
                                                           random_state=42))]),
             n_jobs=-1, param_grid={'model__C': [0.01, 0.1, 1, 10, 100]},
             scoring='recall')

In [69]:
# Displaying the best hyperparameter

print("Best parameter:", grid_search.best_params_)
print("Best cross-validation recall:", grid_search.best_score_)

Best parameter: {'model__C': 1}
Best cross-validation recall: 0.5491638795986622

In [70]:
# Making predictions using the tuned Logistic Regression model

best_logistic_model = grid_search.best_estimator_

y_pred_tuned = best_logistic_model.predict(X_test)

In [71]:
# Evaluating the tuned Logistic Regression model

tuned_logistic_results = {
    'Model': 'Tuned Logistic Regression',
    'Accuracy': accuracy_score(y_test, y_pred_tuned),
    'Precision': precision_score(y_test, y_pred_tuned),
    'Recall': recall_score(y_test, y_pred_tuned),
    'F1 Score': f1_score(y_test, y_pred_tuned)
}

tuned_logistic_results

{'Model': 'Tuned Logistic Regression',
 'Accuracy': 0.8062455642299503,
 'Precision': 0.658307210031348,
 'Recall': 0.5614973262032086,
 'F1 Score': 0.6060606060606061}

In [72]:
# Comparing the original and tuned Logistic Regression models

final_comparison = pd.DataFrame([
    logistic_results,
    random_forest_results,
    gradient_boosting_results,
    tuned_logistic_results
])

final_comparison.sort_values(
    by='F1 Score',
    ascending=False
)

                       Model  Accuracy  Precision    Recall  F1 Score
0        Logistic Regression  0.806246   0.658307  0.561497  0.606061
3  Tuned Logistic Regression  0.806246   0.658307  0.561497  0.606061
2          Gradient Boosting  0.801278   0.662069  0.513369  0.578313
1              Random Forest  0.779276   0.609756  0.467914  0.529501

In [73]:
# Creating the confusion matrix

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_tuned)

cm

array([[926, 109],
       [164, 210]])

In [74]:
# Visualizing the confusion matrix

fig = px.imshow(
    cm,
    text_auto=True,
    x=['Predicted No Churn', 'Predicted Churn'],
    y=['Actual No Churn', 'Actual Churn'],
    title='Confusion Matrix - Tuned Logistic Regression',
    labels={
        'x': 'Predicted',
        'y': 'Actual',
        'color': 'Count'
    }
)

fig.show()

In [75]:
# Generating the classification report

from sklearn.metrics import classification_report

print(classification_report(
    y_test,
    y_pred_tuned,
    target_names=['No Churn', 'Churn']
))

              precision    recall  f1-score   support

    No Churn       0.85      0.89      0.87      1035
       Churn       0.66      0.56      0.61       374

    accuracy                           0.81      1409
   macro avg       0.75      0.73      0.74      1409
weighted avg       0.80      0.81      0.80      1409

In [76]:
# Validating the final model using 5-fold cross-validation

from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(
    best_logistic_model,
    X_train,
    y_train,
    cv=5,
    scoring='recall'
)

print("Cross-validation recall scores:", cv_scores)
print("Mean cross-validation recall:", cv_scores.mean())

Cross-validation recall scores: [0.59531773 0.52173913 0.54180602 0.54180602 0.5451505 ]
Mean cross-validation recall: 0.5491638795986622

In [77]:
# Creating a final evaluation summary

final_metrics = pd.DataFrame({
    'Metric': ['Accuracy', 'Precision', 'Recall', 'F1 Score'],
    'Score': [
        accuracy_score(y_test, y_pred_tuned),
        precision_score(y_test, y_pred_tuned),
        recall_score(y_test, y_pred_tuned),
        f1_score(y_test, y_pred_tuned)
    ]
})

final_metrics

      Metric     Score
0   Accuracy  0.806246
1  Precision  0.658307
2     Recall  0.561497
3   F1 Score  0.606061

In [78]:
import numpy as np
import sklearn
import pandas as pd

print("NumPy:", np.__version__)
print("Scikit-learn:", sklearn.__version__)
print("Pandas:", pd.__version__)

NumPy: 2.4.1
Scikit-learn: 1.8.0
Pandas: 3.0.0

In [79]:
# Saving the final trained model using pickle protocol 4

import pickle

with open('churn_model_v2.pkl', 'wb') as file:
    pickle.dump(
        best_logistic_model,
        file,
        protocol=4
    )

print("Model saved successfully.")

Model saved successfully.

In [80]:
import pickle

with open('churn_model_v2.pkl', 'rb') as file:
    test_model = pickle.load(file)

print("Model loaded successfully!")

Model loaded successfully!

In [81]:
with open('churn_model_v2.pkl', 'rb') as file:
    test_model = pickle.load(file)

print("Model loaded successfully!")

Model loaded successfully!

In [82]:
import sys

print(sys.executable)

c:\Users\ahmed\anaconda3\envs\coursebase\python.exe